theme = "hugo-theme-stack"
baseURL = 'https://lev1ne.org/'
languageCode = 'zh-cn'
title = 'âž°ð“µð“®ð“¿ðŸ­ð“·ð“®'

[module]
  [module.hugoVersion]
    min = ">=0.102.0"
	
[params]
  mainSections = ["posts"]